server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: stay-stylish-logs
    static_configs:
      - targets:
          - localhost # Promtail 컨테이너 자체
        labels:
          job: stay-stylish
          __path__: /var/log/app/*.log

