# ⬇[application-local.yml] - 'local' 프로필

spring:
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.config.parameterstore.ParameterStoreAutoConfiguration
  #  Local DB (PostgreSQL) 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #  Local Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

  mail:
    username: ${EMAIL_USERNAME}      # 로컬 .env 파일에 Gmail 주소
    password: ${EMAIL_PASSWORD}

  #  Swagger
springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    display-request-duration: true
    tryItOutEnabled: true

#  OAuth Redirect URI (로컬용)
app:
  oauth:
    redirect-uri: http://localhost:3000

#  로컬에서만 SQL 상세 로깅 활성화
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
